import assert from'node:assert/strict';
import fs from'node:fs';
import{Game,validSave}from'../dist/engine.js';
import{ROOMS,ZONES,DOOR_POS,DIRS,RELICS,SEQUENCES,VALVES}from'../dist/content.js';
const moves=[[0,-1,'U'],[1,0,'R'],[0,1,'D'],[-1,0,'L']],key=(x,y)=>y*17+x;
function path(g,goal){const s=g.state,q=[[s.x,s.y,'']],seen=new Set([key(s.x,s.y)]);for(let i=0;i<q.length;i++){const[x,y,p]=q[i];if(goal(x,y))return p;for(const[dx,dy,l]of moves){const xx=x+dx,yy=y+dy,k=key(xx,yy);if(seen.has(k)||!g.passable(xx,yy)||g.tile(xx,yy)==='D')continue;if(g.data.revealed&&g.objectsAt(xx,yy).some(o=>o.type==='rune')&&!goal(xx,yy))continue;seen.add(k);q.push([xx,yy,p+l]);}}return null;}
function walk(g,p){assert.notEqual(p,null,`No path in ${g.room.id} from ${g.state.x},${g.state.y}`);for(const l of p){const[dx,dy]=moves.find(m=>m[2]===l);assert(g.move(dx,dy),`Blocked ${l} in ${g.room.id} at ${g.state.x},${g.state.y}`);g.events=[];}}
function approach(g,o){walk(g,path(g,(x,y)=>Math.abs(x-o.x)+Math.abs(y-o.y)<=1));}
function operate(g,o,tool=null){approach(g,o);if(tool){g.equip(tool);g.use(tool,o);}else g.interact(o);g.events=[];}
function solveWeights(g){const d=g.data,crates=d.objects.filter(o=>o.type==='crate').map(o=>key(o.x,o.y)).sort((a,b)=>a-b),goals=d.objects.filter(o=>o.type==='plate').map(o=>key(o.x,o.y));const floor=new Set();for(let y=0;y<13;y++)for(let x=0;x<17;x++)if(g.tile(x,y)==='.')floor.add(key(x,y));const reachable=(p,cs)=>{const q=[[p,'']],map=new Map([[p,'']]),blocked=new Set(cs);for(let i=0;i<q.length;i++){const[k,seq]=q[i],x=k%17,y=Math.floor(k/17);for(const[dx,dy,l]of moves){const n=key(x+dx,y+dy);if(!floor.has(n)||blocked.has(n)||map.has(n))continue;map.set(n,seq+l);q.push([n,seq+l]);}}return map;};
 const first={p:key(g.state.x,g.state.y),cs:crates,seq:''},q=[first],seen=new Set();for(let i=0;i<q.length;i++){const cur=q[i];if(goals.every(k=>cur.cs.includes(k)))return cur.seq;const reach=reachable(cur.p,cur.cs),stateKey=cur.cs.join(',')+'|'+Math.min(...reach.keys());if(seen.has(stateKey))continue;seen.add(stateKey);assert(seen.size<300000,'Weight puzzle search exceeded bound: '+g.room.id);for(let j=0;j<cur.cs.length;j++){const k=cur.cs[j],x=k%17,y=Math.floor(k/17);for(const[dx,dy,l]of moves){const from=key(x-dx,y-dy),to=key(x+dx,y+dy);if(!reach.has(from)||!floor.has(to)||cur.cs.includes(to))continue;const xx=to%17,yy=Math.floor(to/17);if(!goals.includes(to)){const b=(a,b)=>!floor.has(key(a,b));if((b(xx-1,yy)||b(xx+1,yy))&&(b(xx,yy-1)||b(xx,yy+1)))continue;}const cs=[...cur.cs];cs[j]=to;cs.sort((a,b)=>a-b);q.push({p:k,cs,seq:cur.seq+reach.get(from)+l});}}}throw Error('Unsolvable weights: '+g.room.id);}
const solutions={};
function solve(g){const r=g.room,d=g.data;
 if(r.type==='weights'){g.resetRoom();const seq=solveWeights(g);solutions[r.variant]=seq;walk(g,seq);}
 if(r.type==='sequence')for(const i of SEQUENCES[r.variant])operate(g,d.objects.find(o=>o.type==='brazier'&&o.index===i),'lantern');
 if(r.type==='vines'){for(const seed of d.objects.filter(o=>o.type==='seed')){let tries=0;while(!path(g,(x,y)=>Math.abs(x-seed.x)+Math.abs(y-seed.y)<=1)&&tries++<30){const vines=d.objects.filter(o=>o.type==='vine'&&!o.removed);const v=vines.find(o=>path(g,(x,y)=>Math.abs(x-o.x)+Math.abs(y-o.y)<=1)!==null);assert(v,'No reachable vine');operate(g,v,'blade');}operate(g,seed);}}
 if(r.type==='runes'){g.use('lantern');for(const i of SEQUENCES[r.variant]){const o=d.objects.find(o=>o.type==='rune'&&o.index===i);walk(g,path(g,(x,y)=>x===o.x&&y===o.y));}}
 if(r.type==='anchors'){const rings=d.objects.filter(o=>o.type==='anchor');const first=rings[0];walk(g,path(g,(x,y)=>x===first.x&&y===first.y));for(const a of rings.slice(1)){assert(a.x===g.state.x||a.y===g.state.y,'Nonlinear hook route');g.state.face=[Math.sign(a.x-g.state.x),Math.sign(a.y-g.state.y)];g.use('hook');assert.equal(g.state.x,a.x,'Hook x');assert.equal(g.state.y,a.y,'Hook y');}}
 if(r.type==='valves'){for(let i=0;i<3;i++){const o=d.objects.find(o=>o.type==='valve'&&o.index===i);for(let n=0;n<VALVES[r.variant][i];n++)operate(g,o);}operate(g,d.objects.find(o=>o.type==='sluice'));}
 if(r.type==='mirrors'){const mirrors=d.objects.filter(o=>o.type==='mirror'),old=mirrors.map(o=>o.angle);d.lit=true;let target=null;for(let mask=0;mask<2**mirrors.length;mask++){mirrors.forEach((o,i)=>o.angle=mask>>i&1);if(g.beam().hit){target=mirrors.map(o=>o.angle);break;}}assert(target,'Unsolvable mirror route: '+r.id);mirrors.forEach((o,i)=>o.angle=old[i]);d.lit=false;operate(g,d.objects.find(o=>o.type==='source'),'prism');for(let i=0;i<mirrors.length;i++)if(mirrors[i].angle!==target[i])operate(g,mirrors[i]);}
 if(r.type==='resonance'){const n=d.notes.length;let target=null;for(let mask=0;mask<2**n;mask++){const a=[...d.notes],seq=[];for(let i=0;i<n;i++)if(mask>>i&1){seq.push(i);for(const j of new Set([(i+n-1)%n,i,(i+1)%n]))a[j]=1-a[j];}if(a.every(Boolean)){target=seq;break;}}assert(target,'Unsolvable resonance: '+r.id);for(const i of target)operate(g,d.objects.find(o=>o.type==='resonator'&&o.index===i),'bell');}
 if(r.type==='timed'){const clock=d.objects.find(o=>o.type==='clock');operate(g,clock);g.use('hourglass');if(r.variant==='time2'){walk(g,path(g,(x,y)=>x===4&&y===8));g.state.face=[1,0];g.use('hook');assert.equal(g.state.x,8);}const seed=d.objects.find(o=>o.type==='seed');operate(g,seed);}
 assert(g.data.solved,`Puzzle did not solve: ${r.id}`);}
const game=new Game();assert.equal(Object.keys(ROOMS).length,47);assert(validSave(game.snapshot()));assert(!validSave({}));
for(let z=0;z<ZONES.length;z++){
 const zone=ZONES[z];if(z<4){const e=game.room.type==='hub'?{dir:['N','E','S','W'][z],to:zone.id+'-0',need:z}:null;assert(e&&game.allowedExit(e),'Region should unlock');}game.enter(zone.id+'-0');const relic=game.data.objects.find(o=>o.type==='relic');operate(game,relic);assert(game.has(zone.relic));
 for(let i=1;i<=6;i++){const id=zone.id+'-'+i;game.enter(id);assert(game.passable(game.state.x,game.state.y),'Unsafe room spawn '+id);solve(game);const d=game.data;assert(d.solved);const serialized=JSON.parse(JSON.stringify(game.snapshot()));const restored=new Game(serialized);assert.deepEqual(restored.snapshot(),game.snapshot(),'Save roundtrip');console.log('PASS',id,game.room.name);}
 game.enter(zone.id+'-8');game.use('lantern');operate(game,game.data.objects.find(o=>o.type==='chest'));assert(game.state.memories.includes(z));
 game.enter(zone.id+'-7');operate(game,game.data.objects.find(o=>o.type==='beacon'));assert(game.state.beacons.includes(z));operate(game,game.data.objects.find(o=>o.type==='return'));assert.equal(game.state.room,'hub');
}
operate(game,game.data.objects.find(o=>o.type==='hearth'));assert.equal(game.state.room,'hearth');operate(game,game.data.objects.find(o=>o.type==='hearth'));assert(game.state.ended);assert.equal(game.state.beacons.length,5);assert.equal(game.state.memories.length,5);
const g=new Game();g.state.relics=Object.keys(RELICS);g.enter('grove-1');g.resetRoom();const before=g.snapshot();walk(g,'U');g.undo();assert.deepEqual(g.snapshot(),before,'Undo restores exact state');walk(g,'U');const badBefore=g.snapshot();assert.equal(g.move(1,0),false);assert.equal(g.state.steps,badBefore.steps,'Blocked move must not advance time');
for(const [id,r] of Object.entries(ROOMS)){const q=new Game();q.state.relics=Object.keys(RELICS);q.enter(id);const d=q.data;assert(d.grid.length===13&&d.grid.every(row=>row.length===17),'Grid dimensions '+id);assert(q.passable(q.state.x,q.state.y),'Default spawn '+id);for(const o of d.objects)assert(o.x>0&&o.x<16&&o.y>0&&o.y<12,'Object bounds '+id);}
fs.writeFileSync(new URL('../dist/solutions.json',import.meta.url),JSON.stringify(solutions,null,2)+'\n');console.log(`Campaign complete: 30 trials, 6 relics, 5 memories, 5 beacons, final ending. ${game.state.steps} simulated footsteps.`);
